[package]
name = "subset"
version = "0.1.0"
authors = ["Elias Trummer <trueld17@htl-kaindorf.ac.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.10.0"